.TH envs.net 7 "9 June 2019" "version 1.0" "Overview of envs.net"

.SH NAME
envs.net

.SH DESCRIPTION
envs.net is a minimalist, non-commercial 
shared linux system and will always be free to use.

.SH BUGS
Of course there are bugs. But we address them as they are found.  If you notice anything 
that doesn't look right, you can help by hopping onto IRC and letting an admin know 
right away (in the #envs channel). Thank you for helping envs.net be the best it can be.

.SH AUTHOR
envs.net by ~creme < creme@envs.net >

.SH SEE ALSO
There are many other utilities to try from the command line, including:

.TP
.B envs
manage your users_info.json entrys and user-submitted scripts
.TP
.B pb
command line pastebin: man pb or pb -h for options (https://envs.sh)
.TP
.B gomuks
a terminal based matrix client written in go
.TP
.B weechat
the extensible chat client
.TP
.B chat
weechat alias
.TP
.B irssi
a modular irc client for unix
.TP
.B webirc
add your webchat account for our thelounge
.TP
.B mutt
command line mail client for @envs.net mail
.TP
.B alpine
alternate command line mail client based on pine
.TP
.B clinte
community notices system
.TP
.B bbj
command line bbs ( bulletin board and jelly )
.TP
.B linkulator
a link aggregator - gopher://envs.net/1/linkulator/
.TP
.B talk
old school chat utility (man talk for more info)
.TP
.B who
see who else is connected right now
.TP
.B finger
get info on other users (local and remote)
.TP
.B twtxt
minimalist microblogging service - see twtxt --help
.TP
.B todo-txt
simple todo managing - see todo-txt --help
.TP
.B burrow
manage your gopherhole - try burrow -h to see the options
.TP
.B hole
open our envs.net gopherhole
.TP
.B toot
command-line fediverse client
.TP
.B feels
envs.net blogging platform: forked from tilde.town/~endorphant's
.TP
.B bb
envs.net bashblog tool - see https://help.envs.net/blog/#with-bashblog
