.TH envs.net 7 "9 June 2019" "version 1.0" "Overview of envs.net"

.SH NAME
envs.net

.SH DESCRIPTION
envs.net is a minimalist, non-commercial 
shared unix system and will always be free to use.

.SH BUGS
Of course there are bugs. But we address them as they are found.  If you notice anything 
that doesn't look right, you can help by hopping onto IRC and letting an admin know 
right away (in the #envs channel). Thank you for helping envs.net be the best it can be.

.SH AUTHOR
envs.net was set up by ~creme.

.SH SEE ALSO
There are many other utilities to try from the command line, including:

weechat   - talk to other cool people on irc

chat - weechat alias

irssi - a modular irc client for unix

webirc - add your webchat account for our thelounge

mutt - command line mail client for @envs.net mail

alpine - alternate command line mail client based on pine

clinte - community notices system

bbj - command line bbs (bulletin board and jelly)

talk - old school chat utility (man talk for more info)

who - see who else is connected right now

finger - get info on other users (local and remote)

envs - manage your users_info.json entrys and user-submitted scripts

envs_toot - submit a post to the official envs.net mastodon account (https://tilde.zone/@envs)

pb - command line pastebin: man pb or pb -h for options (https://envs.sh)

twtxt - minimalist microblogging service - see twtxt --help

todo-txt - simple todo managing - see todo-txt --help

burrow - manage your gopherhole - try burrow -h to see the options

hole - open our envs.net gopherhole

feels - envs.net blogging platform: forked from tilde.town/~endorphant's

bb - envs.net bashblog tool - see https://envs.net/help/blog/#with-bashblog
